--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_azurefirewall
  description: Delete Azure Firewall
  code:
    resource_group: myResourceGroup
    name: myAzureFirewall
    state: absent
  