--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_eventgrideventsubscription
  description: EventSubscriptions_UpdateForResourceGroup
  code:
    scope: subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourceGroups/examplerg
    name: examplesubscription2
  