--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementproperty
  description: ApiManagementDeleteProperty
  code:
    resource_group: myResourceGroup
    service_name: myService
    prop_id: myProperty
    state: absent
  