--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_servicebusmigrationconfig_info
  description: MigrationConfigurationsList
  code:
    resource_group: myResourceGroup
    namespace_name: my
    name: $default
  