--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_frontdoorbackendpool
  description: Delete Backend Pool
  code:
    resource_group: myResourceGroup
    front_door_name: myFrontDoor
    name: myBackendPool
    state: absent
  