--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapirelease_info
  description: ApiManagementListApiReleases
  code:
    resource_group: myResourceGroup
    name: myService
    api_id: myApis
  