--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapioperationpolicy
  description: ApiManagementDeleteApiOperationPolicy
  code:
    resource_group: myResourceGroup
    name: myService
    api_id: myApis
    operation_id: myOperation
    policy_id: myPolicy
    state: absent
  