--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementproduct_info
  description: ApiManagementGetProduct
  code:
    resource_group: myResourceGroup
    name: myService
    product_id: myProduct
  