--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementauthorizationserver_info
  description: ApiManagementGetAuthorizationServer
  code:
    resource_group: myResourceGroup
    name: myService
    authsid: myAuthorizationServer
  