--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_frontdoorroutingrule
  description: Create or update specific Redirect Routing Rule
  code:
    resource_group: myResourceGroup
    front_door_name: myFrontDoor
    name: myRoutingRule
    routing_rule_parameters:
      name: redirectRoutingRule1
      properties:
        frontendEndpoints:
          - id: >-
              /subscriptions/{{ subscription_id }}/resourceGroups/{{
              resource_group }}/providers/Microsoft.Network/frontDoors/{{
              front_door_name }}/frontendEndpoints/{{ frontend_endpoint_name }}
          - id: >-
              /subscriptions/{{ subscription_id }}/resourceGroups/{{
              resource_group }}/providers/Microsoft.Network/frontDoors/{{
              front_door_name }}/frontendEndpoints/{{ frontend_endpoint_name }}
        acceptedProtocols:
          - Https
        patternsToMatch:
          - /*
        routeConfiguration:
          '@odata.type': '#Microsoft.Azure.FrontDoor.Models.FrontdoorRedirectConfiguration'
          redirectType: Moved
          redirectProtocol: HttpsOnly
          customHost: www.bing.com
          customPath: /api
          customFragment: fragment
          customQueryString: a=b
        enabledState: Enabled
  