--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_batchapplication
  description: ApplicationUpdate
  code:
    resource_group: myResourceGroup
    account_name: myBatchAccount
    name: myApplication
    display_name: myAppName
    allow_updates: true
    default_version: '2'
  