--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_frontdoorfrontendendpoint
  description: Create or update specific Frontend Endpoint
  code:
    resource_group: myResourceGroup
    front_door_name: myFrontDoor
    name: myFrontendEndpoint
    frontend_endpoint_parameters:
      name: frontendEndpoint1
      properties:
        hostName: www.contoso.com
        sessionAffinityEnabledState: Enabled
        sessionAffinityTtlSeconds: '60'
        webApplicationFirewallPolicyLink:
          id: >-
            /subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group
            }}/providers/Microsoft.Network/frontDoorWebApplicationFirewallPolicies/{{
            front_door_web_application_firewall_policy_name }}
  