--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_softwareupdateconfiguration
  description: Delete software update configuration
  code:
    resource_group: myResourceGroup
    automation_account_name: myAutomationAccount
    name: mySoftwareUpdateConfiguration
    state: absent
  