--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_softwareupdateconfiguration
  description: Create software update configuration
  code:
    resource_group: myResourceGroup
    automation_account_name: myAutomationAccount
    name: mySoftwareUpdateConfiguration
    update_configuration:
      operating_system: Windows
      windows:
        included_update_classifications: Critical
        excluded_kb_numbers:
          - '168934'
          - '168973'
        reboot_setting: IfRequired
      duration: PT2H0M
      azure_virtual_machines:
        - >-
          /subscriptions/5ae68d89-69a4-454f-b5ce-e443cc4e0067/resourceGroups/myresources/providers/Microsoft.Compute/virtualMachines/vm-01
        - >-
          /subscriptions/5ae68d89-69a4-454f-b5ce-e443cc4e0067/resourceGroups/myresources/providers/Microsoft.Compute/virtualMachines/vm-02
        - >-
          /subscriptions/5ae68d89-69a4-454f-b5ce-e443cc4e0067/resourceGroups/myresources/providers/Microsoft.Compute/virtualMachines/vm-03
      non_azure_computer_names:
        - box1.contoso.com
        - box2.contoso.com
      targets:
        azure_queries:
          - scope:
              - >-
                /subscriptions/5ae68d89-69a4-454f-b5ce-e443cc4e0067/resourceGroups/myresources
              - /subscriptions/5ae68d89-69a4-454f-b5ce-e443cc4e0067
            locations:
              - Japan East
              - UK South
        non_azure_queries:
          - {}
          - {}
    schedule_info:
      start_time: '2017-10-19T12:22:57+00:00'
      expiry_time: '2018-11-09T11:22:57+00:00'
      interval: '1'
      frequency: Hour
      time_zone: America/Los_Angeles
      advanced_schedule:
        week_days:
          - Monday
          - Thursday
    tasks:
      pre_task:
        source: HelloWorld
      post_task:
        source: GetCache
  