--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_computegallery_info
  description: List galleries in a resource group.
  code:
    resource_group: myResourceGroup
  