--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementservice
  description: ApiManagementCreateMultiRegionServiceWithCustomHostname
  code:
    resource_group: myResourceGroup
    name: myService
    hostname_configurations:
      - type: Proxy
        host_name: proxyhostname1.contoso.com
        encoded_certificate: '************Base 64 Encoded Pfx Certificate************************'
        certificate_password: >-
          **************Password of the
          Certificate************************************************
      - type: Proxy
        host_name: proxyhostname2.contoso.com
        encoded_certificate: '************Base 64 Encoded Pfx Certificate************************'
        certificate_password: >-
          **************Password of the
          Certificate************************************************
        negotiate_client_certificate: true
      - type: Portal
        host_name: portalhostname1.contoso.com
        encoded_certificate: '************Base 64 Encoded Pfx Certificate************************'
        certificate_password: >-
          **************Password of the
          Certificate************************************************
    virtual_network_configuration:
      subnet_resource_id: >-
        /subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group
        }}/providers/Microsoft.Network/virtualNetworks/{{ virtual_network_name
        }}/subnets/{{ subnet_name }}
    additional_locations:
      - location: West US
        sku:
          name: Premium
          capacity: '1'
        virtual_network_configuration:
          subnet_resource_id: >-
            /subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group
            }}/providers/Microsoft.Network/virtualNetworks/{{ virtual_network_name
            }}/subnets/{{ subnet_name }}
    virtual_network_type: External
    publisher_email: admin@live.com
    publisher_name: contoso
    sku:
      name: Premium
      capacity: '1'
    location: Central US
  