--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapioperation
  description: ApiManagementUpdateApiOperation
  code:
    resource_group: myResourceGroup
    name: myService
    api_id: myApis
    operation_id: myOperation
    template_parameters: []
    request:
      queryParameters:
        - name: param1
          description: >-
            A sample parameter that is required and has a default value of
            "sample".
          type: string
          defaultValue: sample
          required: true
          values:
            - sample
    responses:
      - statusCode: '200'
        description: Returned in all cases.
        representations: []
        headers: []
      - statusCode: '500'
        description: Server Error.
        representations: []
        headers: []
    display_name: Retrieve resource
    method: GET
    url_template: /resource
  