--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_batchpool
  description: UpdatePool - Enable Autoscale
  code:
    resource_group: myResourceGroup
    account_name: myBatchAccount
    name: myPool
    scale_settings:
      auto_scale:
        formula: $TargetDedicatedNodes=34
  