--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_batchpool
  description: DeletePool
  code:
    resource_group: myResourceGroup
    account_name: myBatchAccount
    name: myPool
    state: absent
  