--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_batchpool
  description: CreatePool - Full VirtualMachineConfiguration
  code:
    resource_group: myResourceGroup
    account_name: myBatchAccount
    pool_name: myPool
    vm_size: STANDARD_D4
    deployment_configuration:
      virtual_machine_configuration:
        image_reference:
          publisher: MicrosoftWindowsServer
          offer: WindowsServer
          sku: 2016-Datacenter-SmallDisk
          version: latest
        node_agent_sku_id: batch.node.windows amd64
        windows_configuration:
          enable_automatic_updates: false
        data_disks:
          - lun: '0'
            caching: ReadWrite
          - lun: '1'
            caching: None
        license_type: Windows_Server
    scale_settings:
      auto_scale:
        formula: $TargetDedicatedNodes=1
        evaluation_interval: PT5M
    network_configuration:
      endpoint_configuration:
        inbound_nat_pools:
          - name: testnat
            protocol: TCP
  