--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementusersubscription_info
  description: ApiManagementListUserSubscriptions
  code:
    resource_group: myResourceGroup
    name: myService
    uid: myUser
  