--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementauthorizationserver
  description: ApiManagementUpdateAuthorizationServer
  code:
    resource_group: myResourceGroup
    service_name: myService
    authsid: myAuthorizationServer
    client_secret: updated
    client_id: update
  