--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_frontdoorhealthprobesetting
  description: Delete HealthProbeSettings
  code:
    resource_group: myResourceGroup
    front_door_name: myFrontDoor
    name: myHealthProbeSetting
    state: absent
  