--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapischema_info
  description: ApiManagementListApiSchemas
  code:
    resource_group: myResourceGroup
    name: myService
    api_id: myApis
  