--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapiversionset
  description: ApiManagementCreateApiVersionSet
  code:
    resource_group: myResourceGroup
    name: myService
    version_set_id: myApiVersionSet
    description: Version configuration
    display_name: api set 1
    versioning_scheme: Segment
  