--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementtag_info
  description: ApiManagementGetOperationTag
  code:
    resource_group: myResourceGroup
    name: myService
    tag_id: myTag
    api_id: myApis
    operation_id: myOperation
  