--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapirelease
  description: ApiManagementCreateApiRelease
  code:
    resource_group: myResourceGroup
    service_name: myService
    api_id: >-
      /subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group
      }}/providers/Microsoft.ApiManagement/service/{{ service_name }}/apis/{{
      api_name }}
    release_id: myRelease
    notes: yahooagain
  