--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapi
  description: ApiManagementCreateApiNewVersionUsingExistingApi
  code:
    resource_group: myResourceGroup
    name: myService
    api_id: myApis
    description: >-
      Create Echo API into a new Version using Existing Version Set and Copy all
      Operations.
    api_version: v4
    is_current: true
    api_version_set_id: >-
      /subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group
      }}/providers/Microsoft.ApiManagement/service/{{ service_name
      }}/apiVersionSets/{{ api_version_set_name }}
    subscription_required: true
    source_api_id: >-
      /subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group
      }}/providers/Microsoft.ApiManagement/service/{{ service_name }}/apis/{{
      apis_name }}
    display_name: Echo API2
    service_url: 'http://echoapi.cloudapp.net/api'
    path: echo2
    protocols:
      - http
      - https
  