--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapi
  description: ApiManagementCreateApiWithOpenIdConnect
  code:
    resource_group: myResourceGroup
    name: myService
    api_id: myApis
    description: >-
      This is a sample server Petstore server.  You can find out more about
      Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net,
      #swagger](http://swagger.io/irc/).  For this sample, you can use the api key
      `special-key` to test the authorization filters.
    authentication_settings:
      openid:
        openidProviderId: testopenid
        bearerTokenSendingMethods:
          - authorizationHeader
    subscription_key_parameter_names:
      header: Ocp-Apim-Subscription-Key
      query: subscription-key
    display_name: Swagger Petstore
    service_url: 'http://petstore.swagger.io/v2'
    path: petstore
    protocols:
      - https
  