--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_batchcertificate
  description: CreateCertificate - Minimal Cer
  code:
    resource_group: myResourceGroup
    account_name: myBatchAccount
    name: myCertificate
    format: Cer
    data: MIICrjCCAZagAwI...
  