--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_frontdoorloadbalancingsetting
  description: Delete LoadBalancingSettings
  code:
    resource_group: myResourceGroup
    front_door_name: myFrontDoor
    name: myLoadBalancingSetting
    state: absent
  