--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_eventgrideventsubscription_info
  description: EventSubscriptions_ListGlobalByResourceGroup
  code:
    resource_group: myResourceGroup
  