--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementbackend
  description: ApiManagementUpdateBackend
  code:
    resource_group: myResourceGroup
    service_name: myService
    backend_id: myBackend
    description: description5308
    tls:
      validate_certificate_chain: false
      validate_certificate_name: true
  