--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementbackend
  description: ApiManagementDeleteBackend
  code:
    resource_group: myResourceGroup
    name: myService
    backend_id: myBackend
    state: absent
  