--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementproperty_info
  description: ApiManagementGetProperty
  code:
    resource_group: myResourceGroup
    name: myService
    prop_id: myProperty
  