--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementlogger
  description: ApiManagementDeleteLogger
  code:
    resource_group: myResourceGroup
    service_name: myService
    logger_id: myLogger
    state: absent
  