--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_batchcertificate_info
  description: Get Certificate with Deletion Error
  code:
    resource_group: myResourceGroup
    account_name: myBatchAccount
    name: myCertificate
  