--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementtag
  description: ApiManagementDeleteTag
  code:
    resource_group: myResourceGroup
    service_name: myService
    tag_id: myTag
    state: absent
  