--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_batchcertificate
  description: CreateCertificate - Full
  code:
    resource_group: myResourceGroup
    account_name: myBatchAccount
    name: myCertificate
    thumbprint_algorithm: SHA1
    thumbprint: 0A0E4F50D51BEADEAC1D35AFC5116098E7902E6E
    format: Pfx
    data: MIIJsgIBAzCCCW4GCSqGSIb3DQE...
    password: KG0UY40e...
  