--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementsubscription
  description: ApiManagementCreateSubscription
  code:
    resource_group: myResourceGroup
    name: myService
    sid: testsub
    owner_id: >-
      /subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group
      }}/providers/Microsoft.ApiManagement/service/{{ service_name }}/users/{{
      user_name }}
    scope: >-
      /subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group
      }}/providers/Microsoft.ApiManagement/service/{{ service_name }}/products/{{
      product_name }}
    display_name: testsub
  