--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_automationjob_info
  description: Get Job Output
  code:
    resource_group: myResourceGroup
    automation_account_name: myAutomationAccount
    name: myJob
  